version: "3.9"

services:
  frontend:
    build:
      context: /home/ec2-user/app/frontend
      dockerfile: Dockerfile
    container_name: chinook_frontend
    restart: always
    ports:
      - "80:80"